"""empty message

Revision ID: a29351cb6774
Revises: 9eeaf32e294a
Create Date: 2024-07-25 02:04:14.055168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29351cb6774'
down_revision = '9eeaf32e294a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esta_activa', sa.Boolean(), nullable=True))

    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esta_activa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_column('esta_activa')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('esta_activa')

    # ### end Alembic commands ###
